name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Get git commit SHA
      id: vars
      run: echo "COMMIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV

    - name: Build and Push Docker Image for Multi-Architecture
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7  
        tags: |
          kaspersvend/cv:latest
          kaspersvend/cv:${{ env.COMMIT_SHA }}