name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2
    
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    
    - name: Build and Push Docker Image
      uses: docker/build-push-action@v3
      with:
        push: true
        platforms: linux/arm64
        tags: |
          kaspersvend/cv:${{ github.sha }}
          kaspersvend/cv:latest
          kaspersvend/cv:v${{ github.run_number }}.0.0